-- Run: nvim --headless '+luafile tests/statusline.lua'
vim.schedule(function()
  local root = vim.fn.tempname() .. '-statusline'
  local ok, err = xpcall(function()
    vim.o.columns = 160
    vim.fn.mkdir(root .. '/repo', 'p')
    local function git(...)
      local args = { 'git', '-C', root .. '/repo' }
      vim.list_extend(args, { ... })
      local result = vim.system(args, { text = true }):wait()
      assert(result.code == 0, result.stderr)
    end
    git('init', '-q', '-b', 'main')
    git('config', 'user.name', 'Test')
    git('config', 'user.email', 'test@example.invalid')
    vim.fn.writefile({ 'before' }, root .. '/repo/file.txt')
    git('add', '.')
    git('-c', 'commit.gpgsign=false', '-c', 'core.hooksPath=/dev/null', 'commit', '-qm', 'Fixture')
    vim.cmd.edit(vim.fn.fnameescape(root .. '/repo/file.txt'))
    local buf = vim.api.nvim_get_current_buf()
    local statusline = require('mini.statusline')
    local function branch(name)
      assert(vim.wait(5000, function()
        return (vim.b[buf].minigit_summary or {}).head_name == name
      end, 20), 'Git tracking did not update to ' .. name)
      local content = statusline.active()
      local rendered = vim.api.nvim_eval_statusline(content, { maxwidth = 160 }).str
      local _, alignment = content:find('%%=')
      local position = assert(rendered:find(name, 1, true), 'Branch is missing: ' .. rendered)
      assert(alignment and content:find(name:gsub('%%', '%%%%'), alignment + 1, true), 'Branch is not right aligned')
      assert(not rendered:find(name, position + #name, true), 'Branch is duplicated')
      assert(vim.trim(rendered:sub(position)) == name, 'Branch is not the final section: ' .. rendered)
      assert(rendered:find('1:1', 1, true), 'Cursor position was lost')
      assert(statusline.section_git({ trunc_width = 0 }):find(name:gsub('%%', '%%%%'), 1, true), 'Built-in Git section was bypassed')
    end
    branch('main')
    vim.fn.writefile({ 'after' }, root .. '/repo/file.txt')
    assert(vim.wait(5000, function() return (vim.b[buf].minigit_summary or {}).status == ' M' end, 20), 'File status did not update')
    assert(vim.b[buf].minigit_summary_string == 'main', 'File status leaked into the branch display')
    git('switch', '-qc', 'feature%{1+1}')
    branch('feature%{1+1}') -- Percent signs must render as text, not statusline expressions.
    git('switch', '-q', '--detach')
    branch('HEAD')
    git('switch', '-q', 'main')
    branch('main')
    vim.fn.writefile({ 'outside Git' }, root .. '/outside.txt')
    vim.cmd.edit(vim.fn.fnameescape(root .. '/outside.txt'))
    assert(statusline.section_git({ trunc_width = 0 }) == '', 'Non-Git file shows a stale branch')
    vim.api.nvim_set_current_buf(buf)
    branch('main')
    assert(vim.v.errmsg == '', vim.v.errmsg)
    print('PASS statusline: branch at far right, cursor position, branch-only summary, live switches, percent escaping, detached HEAD, non-Git file')
  end, debug.traceback)
  vim.fn.delete(root, 'rf')
  if ok then vim.cmd('qa!') else vim.api.nvim_err_writeln(err); vim.cmd('cquit 1') end
end)
